-- Table for employee details
CREATE TABLE Employees (
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(255),
    EMPLOYEE_PHONE VARCHAR(255),
    EMPLOYEE_DOB DATE,
    EMAIL_ID VARCHAR(255) UNIQUE,
    MANAGER_ID INTEGER,
    GENDER VARCHAR(255)
    FOREIGN KEY (MANAGER_ID) REFERENCES Employees(EMPLOYEE_ID)
);

-- Table for employee email and password
CREATE TABLE USERS (
    EMAIL_ID VARCHAR(255) PRIMARY KEY,
    PASSWORD VARCHAR(255),
    FOREIGN KEY (EMAIL_ID) REFERENCES EMPLOYEES(EMAIL_ID)
);


-- Table for leave details
CREATE TABLE Leaves (
    LEAVE_ID INTEGER PRIMARY KEY,
    EMPLOYEE_ID INTEGER,
    LEAVE_FROM DATE,
    LEAVE_TO DATE,
    LEAVE_TYPE VARCHAR(255),
    LEAVE_REASON VARCHAR(255),
    LEAVE_STATUS VARCHAR(255),
    DAYS_TAKEN INTEGER,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES Employees(EMPLOYEE_ID)
);

-- Table for leave type limits
CREATE TABLE LEAVES_TYPE (
    LEAVE_TYPE VARCHAR(255) PRIMARY KEY,
    LEAVE_LIMIT INTEGER,
);

-- Table for holiday details
CREATE TABLE Holidays (
    HOLIDAY_NAME VARCHAR(255),
    FROM_DATE DATE,
    TO_DATE DATE,
    HOLIDAY_TYPE VARCHAR(255),
    DAYS_COUNT INTEGER,
    PRIMARY KEY (HOLIDAY_NAME, FROM_DATE)
);